### ISSUE TITLE
fail syncing repo.

### ISSUE THREAD

**Issue by ALoGeNo** [aopp/android_platform#5]
Shared project CyanogenMod/android_hardware_qcom_audio found, disabling pruning.
Traceback (most recent call last):903)   ng out files:   2% (644/28903)
  File "/media/by314/K4L1/aopp/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/media/by314/K4L1/aopp/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/media/by314/K4L1/aopp/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/media/by314/K4L1/aopp/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/media/by314/K4L1/aopp/.repo/repo/project.py", line 1327, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/media/by314/K4L1/aopp/.repo/repo/project.py", line 2486, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
by314@ORION:/media/by314/K4L1/aopp$

**Comment by ALoGeNo** [comment]
Solved.

**Comment by DeSharky** [comment]
How?
